### ISSUE TITLE
500 document is not defined

### ISSUE THREAD

**Issue by goodforever** [benmccann/sveltekit-bytemd-bug-reproduction#1]
After npm install  & npm run dev
visit localhost:3000
got error:

500
document is not defined
ReferenceError: document is not defined
    at /node_modules/bytemd/svelte/helpers.js:17032:19
    at instantiateModule (/Users/foo/svelte/sveltekit-bytemd-bug-reproduction/node_modules/vite/dist/node/chunks/dep-9c153816.js:56193:15)

**Comment by benmccann** [comment]
this repository is to demonstrate a bug
